global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
remote_write:
- url: https://prometheus-prod-25-prod-sa-east-0.grafana.net/api/prom/push
  basic_auth:
    username: 930391
    password: eyJrIjoiNDViZjExYjI1YTQ4NjY3MDI3OGE2MTk2YTVlMGMwY2MxNDA3MDdhZiIsIm4iOiJwcm9tZXRoZXVzIiwiaWQiOjExNDMwOX0=